[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[project]
name = "REU_temp"
version = "0.1.0"
description = "A Demo for my stackoverflow question"
dependencies = [
    "shutils",
]
