[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[project]
name = "REU_temp"
dynamic = ["version"]
description = "A Demo for my stackoverflow question"
dependencies = [
    "shutils",
]

[tool.hatch.version]
path = "REU_temp/__about__.py"
