name: bump version
on: workflow_dispatch
# on: push
#on: release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: automatically release main branch
        run: |
          git config --global user.name 'drscook'
          git config --global user.email 'scook@tarleton.edu'
          VERSION=`hatch version`
          hatch version patch
          NEW_VERSION=`hatch version`
          git add REU_temp/__about__.py
          git commit -m "Bump version: $VERSION → $NEW_VERSION"
          git tag $VERSION
          git push
          git push --tags
