# taken and upgraded from:
# https://github.com/haddocking/pdb-tools/blob/f019d163d8f8cc5a0cba288e02f5a63a969719f6/.github/workflows/bump-version-on-push.yml
name: version bump and deploy

on: workflow_dispatch
jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Setup Git
      run: |
        git config user.name "drscook"
        git config user.email 'scook@tarleton.edu'
        git remote set-url origin https://x-access-token:${{ secrets.GHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout "${GITHUB_REF:11}"
